import React,{useEffect,useRef} from 'react';
// Bundled first-party Three.js ESM, Copyright 2010-2025 Three.js Authors, MIT.
// @ts-ignore packaged ESM runtime module
import * as T from 'three';
export function ThreeWorld({progress,paused,reduced,look}:{progress:number;paused:boolean;reduced:boolean;look:{x:number;y:number}}){
 const mount=useRef<HTMLDivElement>(null),state=useRef({progress,paused,reduced,look});
 useEffect(()=>{state.current={progress,paused,reduced,look}},[progress,paused,reduced,look]);
 useEffect(()=>{
  const host=mount.current;if(!host)return;
  let renderer:any;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'})}catch{return}
  renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(renderer.domElement);
  const scene=new T.Scene();scene.background=new T.Color(0xd9ebdf);
  const camera=new T.PerspectiveCamera(43,host.clientWidth/host.clientHeight,.1,100);camera.position.set(0,8.6,13.6);camera.lookAt(0,1.2,0);
  scene.add(new T.HemisphereLight(0xffffff,0x718b72,2.15));const sun=new T.DirectionalLight(0xffffff,2);sun.position.set(-4,9,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-12;sun.shadow.camera.right=12;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;scene.add(sun);const warm=new T.PointLight(0xffc67e,32,8);warm.position.set(-1.7,3.1,-2.3);scene.add(warm);const monitorGlow=new T.PointLight(0x4fffd1,24,7);monitorGlow.position.set(.2,1.8,.2);scene.add(monitorGlow);
  const mats={ground:new T.MeshStandardMaterial({color:0xaccbad,roughness:1}),path:new T.MeshStandardMaterial({color:0xe7dcc3,roughness:1}),teal:new T.MeshStandardMaterial({color:0x078c87,roughness:.64}),skin:new T.MeshStandardMaterial({color:0xb8774e,roughness:.8}),hair:new T.MeshStandardMaterial({color:0x191c20,roughness:1}),jeans:new T.MeshStandardMaterial({color:0x24445b,roughness:.9}),metal:new T.MeshStandardMaterial({color:0x394e51,metalness:.4,roughness:.6}),rubber:new T.MeshStandardMaterial({color:0x151b1b,roughness:.98}),white:new T.MeshStandardMaterial({color:0xf6f5e8}),screen:new T.MeshStandardMaterial({color:0x93d2ba,emissive:0x31b08c,emissiveIntensity:.3}),wood:new T.MeshStandardMaterial({color:0x9e755b,roughness:.9}),wall:new T.MeshStandardMaterial({color:0xd5ddc9,roughness:1}),leaf:new T.MeshStandardMaterial({color:0x2d8063,roughness:.9}),sole:new T.MeshStandardMaterial({color:0xeee8d7}),eye:new T.MeshStandardMaterial({color:0x161e1e}),shine:new T.MeshBasicMaterial({color:0xffffff}),gold:new T.MeshStandardMaterial({color:0xf3bd67,metalness:.28}),hood:new T.MeshStandardMaterial({color:0x126b68}),light:new T.MeshStandardMaterial({color:0xffffff,emissive:0xffdba0,emissiveIntensity:.9})};
  const box=(parent:any,w:number,h:number,d:number,m:any,x:number,y:number,z:number)=>{const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
  const ball=(parent:any,r:number,m:any,x:number,y:number,z:number,seg=12)=>{const o=new T.Mesh(new T.SphereGeometry(r,seg,8),m);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o};
  const ground=new T.Mesh(new T.PlaneGeometry(18,18),mats.ground);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
  // An oval track through five landmarks. The central workspace makes the theme legible in 3D.
  const curve=new T.CatmullRomCurve3([new T.Vector3(-5,0,2.7),new T.Vector3(-3,0,-3.3),new T.Vector3(0,0,-4.2),new T.Vector3(3.3,0,-3),new T.Vector3(5,0,2.8),new T.Vector3(2,0,4.5),new T.Vector3(-2,0,4.3)],true,'centripetal');
  const points=curve.getPoints(180),vertices=[] as number[];for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],v=b.clone().sub(a).normalize(),n=new T.Vector3(-v.z,0,v.x),w=.68;vertices.push(...a.clone().addScaledVector(n,w).toArray(),...a.clone().addScaledVector(n,-w).toArray(),...b.clone().addScaledVector(n,w).toArray(),...b.clone().addScaledVector(n,w).toArray(),...a.clone().addScaledVector(n,-w).toArray(),...b.clone().addScaledVector(n,-w).toArray())}const pathGeo=new T.BufferGeometry();pathGeo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));pathGeo.computeVertexNormals();const path=new T.Mesh(pathGeo,new T.MeshStandardMaterial({color:0xe8d4ae,side:T.DoubleSide}));path.position.y=.02;scene.add(path);
  const room=new T.Group();scene.add(room);box(room,3.4,.15,1.4,mats.metal,0,.8,0);for(const x of [-1.45,1.45])for(const z of [-.48,.48])box(room,.12,.83,.12,mats.metal,x,.42,z);box(room,1.3,.85,.09,mats.metal,0,1.42,-.35);box(room,1.15,.7,.06,mats.screen,0,1.44,-.29);box(room,.25,.12,.2,mats.metal,0,.95,-.26);box(room,1.12,2.7,1.08,mats.metal,2.65,1.35,-.35);for(let i=0;i<7;i++)box(room,.86,.07,.02,mats.screen,2.65,.45+i*.29,.21);for(let i=0;i<4;i++){const shrub=new T.Group();shrub.position.set(-3+i*2,0,1.15);scene.add(shrub);box(shrub,.5,.4,.5,mats.metal,0,.2,0);ball(shrub,.43,new T.MeshStandardMaterial({color:0x2c8568}),0,.75,0)}
  // Furnish a miniature workstation: tiled plinth, back walls, shelves, books, desk items and trees.
  box(scene,8.5,.16,7.9,mats.wood,0,-.09,0);
  for(let i=0;i<4;i++){box(room,.18,.28,.09,i%2?mats.teal:mats.gold,-1.32+i*.21,.97,-.17)}
box(room,.42,.22,.28,mats.metal,.91,.96,.28);box(room,.26,.04,.19,mats.white,.91,1.09,.28);
  const lamp=new T.Group();lamp.position.set(-1.13,.9,-.35);room.add(lamp);cylinderBetween(lamp,new T.Vector3(0,0,0),new T.Vector3(0,.52,0),.025,mats.metal);const lampShade=ball(lamp,.17,mats.gold,0,.57,0);lampShade.scale.set(1,.4,1);ball(lamp,.09,mats.light,0,.48,0);
  const keyboard=box(room,.7,.035,.23,mats.rubber,0,.91,.28);for(let i=0;i<11;i++)for(let j=0;j<3;j++)box(room,.039,.005,.05,mats.white,-.31+i*.058,.934,.19+j*.065);
  // Wavy hair, brows, eyes, smile and hoodie details in actual 3D geometry.
  const rider=new T.Group();scene.add(rider);const chassis=new T.Group();rider.add(chassis);
  function cylinderBetween(parent:any,a:any,b:any,r:number,material:any){const dir=b.clone().sub(a),o=new T.Mesh(new T.CylinderGeometry(r,r,dir.length(),8),material);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),dir.normalize());parent.add(o);return o}
  const v=(x:number,y:number,z=0)=>new T.Vector3(x,y,z);const rear=v(-.65,.52),front=v(.65,.52),crank=v(0,.53),saddle=v(-.18,1.15),stem=v(.34,1.15);
  const wheels:any[]=[];for(const x of [-.65,.65]){const tor=new T.Mesh(new T.TorusGeometry(.43,.065,8,20),mats.rubber);tor.position.set(x,.52,0);chassis.add(tor);wheels.push(tor);ball(chassis,.07,mats.metal,x,.52,0)}
  for(const [a,b] of [[rear,crank],[crank,front],[rear,saddle],[saddle,stem],[stem,crank],[stem,front]])cylinderBetween(chassis,a,b,.048,mats.teal);
  cylinderBetween(chassis,v(-.43,1.18),v(.01,1.18),.055,mats.rubber);cylinderBetween(chassis,v(.28,1.18),v(.42,1.28),.045,mats.metal);cylinderBetween(chassis,v(.42,1.28,-.24),v(.42,1.28,.24),.043,mats.rubber);
  const hips=new T.Group();hips.position.set(-.2,1.48,0);chassis.add(hips);ball(hips,.22,mats.jeans,0,0,0);const torso=ball(chassis,.44,mats.teal,-.13,2.03,0);torso.scale.set(.8,1.12,.66);ball(chassis,.16,mats.skin,-.09,2.44,0);const head=new T.Group();head.position.set(-.04,2.8,0);chassis.add(head);const face=ball(head,.31,mats.skin,0,0,0,18);face.scale.set(.89,1.06,.83);const hair=ball(head,.32,mats.hair,-.04,.25,-.02);hair.scale.set(1,.45,1);for(const x of [-.14,.14]){ball(head,.038,mats.hair,x,.025,.26);ball(head,.017,mats.white,x+.008,.036,.292)}ball(head,.039,mats.skin,0,-.085,.29);
  for(let i=0;i<9;i++){const angle=i*Math.PI*2/9;const curl=ball(head,.09+(i%3)*.018,mats.hair,Math.cos(angle)*.25,.29+Math.sin(i*2)*.035,Math.sin(angle)*.22);curl.scale.set(1.1,.85,1)}
  for(const x of [-.14,.14]){ball(head,.065,mats.white,x,.045,.275);ball(head,.039,mats.eye,x+.014,.043,.33);ball(head,.014,mats.shine,x+.023,.056,.362);const brow=ball(head,.095,mats.hair,x,.14,.25);brow.scale.set(1,.21,.25)}
  const smile=ball(head,.10,mats.eye,0,-.16,.278);smile.scale.set(1,.18,.22);ball(head,.07,mats.hair,0,-.28,.235);
  const hood=ball(chassis,.33,mats.hood,-.32,2.34,-.06);hood.scale.set(.85,.65,1);for(const z of [-.15,.15])cylinderBetween(chassis,v(-.06,2.37,z),v(-.04,2.03,z),.012,mats.white);
  const pocket=box(chassis,.30,.14,.08,mats.hood,-.14,1.81,.30);pocket.rotation.z=.08;
  for(const z of [-.2,.2])cylinderBetween(chassis,v(-.29,2.25,z),v(.37,1.32,z),.105,mats.teal);
  const legs:any[]=[];for(const z of [-.16,.16]){const upper=new T.Group();upper.position.set(-.19,1.49,z);chassis.add(upper);const thigh=cylinderBetween(upper,v(0,0),v(.25,-.43),.12,mats.jeans);const lower=new T.Group();lower.position.set(.25,-.43,0);upper.add(lower);cylinderBetween(lower,v(0,0),v(-.04,-.45),.09,mats.jeans);box(lower,.35,.12,.2,mats.white,.06,-.9,.06);box(lower,.36,.045,.22,mats.sole,.06,-.97,.06);box(lower,.14,.07,.21,mats.teal,.16,-.88,.06);legs.push({upper,lower,thigh})}
  for(let i=0;i<5;i++){const p=curve.getPoint(i/5),pole=new T.Group();pole.position.set(p.x,0,p.z);scene.add(pole);cylinderBetween(pole,v(0,0),v(0,.9),.07,mats.metal);const marker=new T.Mesh(new T.OctahedronGeometry(.25),new T.MeshStandardMaterial({color:i%2?0x65b8a1:0xf3c772,emissive:i%2?0x186648:0x786020,emissiveIntensity:.25}));marker.position.y=1.1;pole.add(marker)}
  // Trees, shrubs and illuminated stepping stones around the ride without cluttering the route.
  for(let i=0;i<8;i++){const a=i*Math.PI*2/8,x=Math.cos(a)*6.5,z=Math.sin(a)*6.3;const tree=new T.Group();tree.position.set(x,0,z);scene.add(tree);cylinderBetween(tree,v(0,0),v(0,.9),.08,mats.wood);for(let j=0;j<3;j++){const foliage=ball(tree,.42-j*.06,mats.leaf,0,1+j*.28,0);foliage.scale.set(1,.8,1)}}
  for(let i=0;i<24;i++){const p=curve.getPoint(i/24);const stone=box(scene,.16,.025,.16,i%2?mats.white:mats.gold,p.x,.08,p.z);stone.rotation.y=i*.4}
  const resize=new ResizeObserver(()=>{if(!host.clientWidth||!host.clientHeight)return;camera.aspect=host.clientWidth/host.clientHeight;camera.position.set(0,host.clientWidth<600?12:8.6,host.clientWidth<600?17:13.6);camera.lookAt(0,1.2,0);camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)});resize.observe(host);
  let raf=0,last=performance.now();function animate(now:number){const dt=Math.min((now-last)/1000,.1);last=now;const data=state.current,p=curve.getPoint(data.progress),t=curve.getTangent(data.progress);rider.position.set(p.x,.1,p.z);rider.rotation.y=Math.atan2(t.z,t.x)*-1;const pedal=now*.006;for(let i=0;i<legs.length;i++){legs[i].upper.rotation.z=Math.sin(pedal+i*Math.PI)*.38;legs[i].lower.rotation.z=Math.sin(pedal+i*Math.PI+1)*.38}for(const w of wheels)w.rotation.z+=data.paused||data.reduced?0:dt*4;head.rotation.y=data.reduced?0:data.look.x*.018;head.rotation.x=data.reduced?0:data.look.y*.015;renderer.render(scene,camera);raf=requestAnimationFrame(animate)}raf=requestAnimationFrame(animate);
  return()=>{cancelAnimationFrame(raf);resize.disconnect();renderer.dispose();host.removeChild(renderer.domElement);scene.traverse((o:any)=>{o.geometry?.dispose?.()})}
 },[]);
 return <div className="three-canvas" ref={mount} role="img" aria-label="Real-time 3D scene: a low-poly cyclist pedals around a loop of five portfolio stops"/>;
}
